version: '3.8'
services:

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-postgres-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats-server:
    build: stats-service/stats-server
    image: stats-server-image
    container_name: stats-server-container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-postgres-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres